services:
  - type: web
    name: wikipedia-book-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: api.py
      - key: PORT
        value: 80